source 'https://rubygems.org'

gem 'sinatra', '>=1.0'
gem 'sinatra-contrib'
gem 'sinatra-cors'
gem 'rake'
gem 'data_mapper'
gem 'dm-core'
gem 'dm-validations'
gem 'dm-aggregates'
gem 'dm-constraints'
gem 'dm-migrations'
gem 'json', '1.8.6'
gem 'sinatra-cross_origin'
gem 'bcrypt', '~> 3.1.3'
gem'dm-postgres-adapter'
gem 'pg'
gem 'do_postgres','0.10.17'
